### ISSUE TITLE
Lumen Support

### ISSUE THREAD

**Issue by ssx** [swisnl/laravel-graylog2#4]
Hi!

Briliant package, it's worked great for Laravel. What changes would be required to get this compatible with Lumen?

**Comment by barryvanveen** [comment]
Thanks @ssx! We don't usually work with Lumen so we haven't tried this yet. Because of this I would only consider supporting Lumen if it doesn't require mayor changes.

 If you want to try it out that would be super. After skimming through the Lumen documentation I don't see any immediate problems.

**Comment by ssx** [comment]
I've had a quick look through as well, I'll have a look this week in full and PR it if everything works okay!

**Comment by barryvanveen** [comment]
Great!

**Comment by ssx** [comment]
I'll close this issue and open one for the PR if possible. Thanks for your time this evening, much appreciated.
