### ISSUE TITLE
Is it right that GraylogHandler is registered in register method?

### ISSUE THREAD

**Issue by alberto-bottarini** [swisnl/laravel-graylog2#5]
Laravel documentation tells that

> within the register method, you should only bind things into the service container. 

while laravel-graylog2, withing register method, also add handler in monolog...

What do you think about?

**Comment by bbrala** [comment]
Yeah you're right, i think it should be in the boot method which loads after all the ServiceProviders are loaded.

**Comment by alberto-bottarini** [comment]
https://github.com/swisnl/laravel-graylog2/pull/8
